### ISSUE TITLE
retrieve pkg metadata to instead of renaming

### ISSUE THREAD

**Issue by method4tax** [hippie68/pkgrename#1]
Hey, first of all thanks for this great tool.
I am currently looking into automating the process of generating a repository which can be used by https://www.4pt-project.com/ . The Repository requires a name and type to be set ( https://github.com/victorrjimenezz/4PT-Repository#adding-packages ). 

For this it would be great to have the information the pkgrename tool is parsing in a machine-readable form to transform the data into the repository format. 
Right now this does not seem to be possible with pkgrename, is there any way to get the information anyway?
Cheers!

**Comment by hippie68** [comment]
With sfo it should be possible: https://github.com/hippie68/sfo
It can selectively read PKGs' param.sfo data and print it. The type could be determined by reading the CATEGORY key (https://www.psdevwiki.com/ps4/Param.sfo#CATEGORY).

**Comment by method4tax** [comment]
Perfect, exactly what i was looking for! Cheers
