### ISSUE TITLE
-p and --pattern argument don't seem to be working

### ISSUE THREAD

**Issue by JonnieMazda** [hippie68/pkgrename#2]
Program seems to be working great but when I try and add the pattern argument it doesn't want to work.
example if my .bat is this:

pkgrename.exe -r -p "%title% (%title_id%) ({v%app_ver%}) ({SDK%sdk%})" %*

then I will get this:

Entering directory ".\CUSA00000 Example Game-A0100-Scene
     "Example Game.pkg"
=> "(v) (SDK).pkg"

If I remove the pattern argument it works correctly using the default pattern.

**Comment by hippie68** [comment]
Thanks for reporting. It turned out inside .bat files you need to escape the pattern variables' percent signs by changing % to %% each, or otherwise they would be treated specially:

pkgrename.bat
    pkgrename.exe -r -p "%%title%% (%%title_id%%) ({v%%app_ver%%}) ({SDK%%sdk%%})" %*

**Comment by JonnieMazda** [comment]
Awesome, thanks for the quick response! That seemed to fix most of the issues. This program is going to save me a lot of time so thank you.
However I think I found another issue that I think is related to this.
When using the %type% or the %patch% variables on a update.pkg instead of the program just adding "Update" to the file name it seems to want to add both the word "Update" followed by theyapp Version number.
Example: (Update 3.02)
I'm not sure if the program is supposed to be adding the app version or not. If it is intended then I think it works when using the %type% variable however when using %patch% it will output (Update %app_ver%).

I think the issue might be on like 36 of pkgrename.c but I'm pretty bad when it comes to this stuff so am not sure.

**Comment by hippie68** [comment]
Thanks, that was not intended and has now been fixed in version 1.05c.

Users who liked the old behavior can get it back by adding

    --set-type "Game,Update %app_ver%,DLC,App,-"

**Comment by JonnieMazda** [comment]
That seems to have fixed it. Thanks again!
