### ISSUE TITLE
Region

### ISSUE THREAD

**Issue by Rus-666** [hippie68/pkgrename#3]
Maybe you could take the first 2 characters from the %content_id% so region can be part of the file name?

**Comment by hippie68** [comment]
Thanks, that's a good idea. I have implemented it in the latest release.

**Comment by Buzbee** [comment]
I would prefer a country region code of UP=US EP=EU JP=JP &HP=AS for Asia since its for CN & KR and for IP use IN for Internal maybe.

**Comment by hippie68** [comment]
I agree, this is going to be changed.
