### ISSUE TITLE
Recycle Bin Pkg files

### ISSUE THREAD

**Issue by Buzbee** [hippie68/pkgrename#4]
With recursive subdirectories it should skip the recycle bin and other hidden directories.

"$I4IJUED.pkg"
File is not a PKG: "k:\$RECYCLE.BIN\S-1-5-21-775778504-1851103982-645274329-1001\$I4IJUED.pkg".

[process exited with code 1 (0x00000001)]

**Comment by hippie68** [comment]
As a solution, I plan to ignore directories starting with "." or "$".
