### ISSUE TITLE
UTF-8 beta feature characters

### ISSUE THREAD

**Issue by Buzbee** [hippie68/pkgrename#5]
After enabling the UTF-8 beta feature: Settings - Time & Language - Language - Administrative language settings - Changing system locale... - Beta: Use Unicode UTF-8 for worldwide language support I can say rename D.pkg successfully to Déraciné.pkg but i can not rename Déraciné.pkg to something else (without renaming it say back to D.pkg first). 

 "D�racin�.pkg"
Error while opening file "k:\D�racin�.pkg".

[process exited with code 1 (0x00000001)]

**Comment by hippie68** [comment]
Could not reproduce on Windows 10 with the beta feature enabled when using pkgrename from cmd.exe. Are you using an external tool that's passing a wrong file name?

**Comment by Buzbee** [comment]
I am using windows 11. I found a fix. Right clicking on pkgrename.exe and clicking run this program as as administrator and clicking apply and OK on the compatibility tab and then running the BAT file fixes the issue.

**Comment by Buzbee** [comment]
It still has issues it just exits now with [process exited with code 1 (0x00000001)] with administrator privileges without showing

"D�racin�.pkg"
Error while opening file "k:\D�racin�.pkg" now.

**Comment by hippie68** [comment]
Does the error depend on specific command line options, like -r, or would it always happen even if you specify the filename directly? I don't have Windows 11, so this may be hard to troubleshoot.

**Comment by Buzbee** [comment]
I am using the following bat file:

@echo off
pkgrename.exe --yes-to-all --recursive --no-placeholder --underscores --pattern "[%%title_id%%] %%type%% %%title%% %%region%% " --set-type "[BSE],[UPD]_{v%%app_ver%%},[DLC],[APP]_{v%%app_ver%%},[OTH]" k:\

**Comment by hippie68** [comment]
I could reproduce the bug when using the Windows Terminal app, which by default uses PowerShell instead of cmd.exe. I got rid of a third-party library, which hopefully fixes the bug for Windows 11, too. Please let me know if it works now:
[pkgrename.zip](https://github.com/hippie68/pkgrename/files/9388974/pkgrename.zip)

**Comment by Buzbee** [comment]
This seems to fix the issue. Probably unrelated though the program pauses for a few seconds after this dlc
[CUSA04647]_[DLC]_WORLD_OF_FINAL_FANTASY_Topaz_Carbuncle_creature_US.pkg
stating
Nothing to do.
then continues on successfully.

**Comment by hippie68** [comment]
Did the second-long pause happen before the bug fix, too? The program may appear to pause while it is searching additional subdirectories for PKG files. Depending on the HDD speed and number of files, this may take a while - the hardware should be the bottleneck. After the first run the OS should have cached the search, so a second run should rename instantaneously.

**Comment by Buzbee** [comment]
I guess its intended to work this way when no files need to be renamed. I never came across before because of the Déraciné.pkg error or renaming that pkg so it would not error out.

 // Quit if already renamed
    if (option_force == 0 && strcmp(basename, new_basename) == 0) {
      printf("Nothing to do.\n");
      goto exit;
    }

**Comment by hippie68** [comment]
Yes, that is intended. You can hide it with option -c, --compact.
