### ISSUE TITLE
[Request] Can %longname% be included as a pattern?

### ISSUE THREAD

**Issue by oneohthree** [hippie68/pkgrename#7]
Setting this pattern `pattern='$content_id-A${app_ver//.}-V${version//.}.pkg'` in the old bash script I can rename the package with its "longname". Can you include this pattern in the new one?

**Comment by hippie68** [comment]
That's a good idea. I named the pattern variable "%file_id%". I'm not sure if the results are correct when the file is a DLC PKG. DLC files don't have APP_VER, so for now they are renamed to "...-A0000-...". I don't know the official naming rules for DLC PKGs.
