### ISSUE TITLE
Backport question

### ISSUE THREAD

**Issue by pearlxcore** [hippie68/pkgrename#8]
Not an issue but how the program detect the pkg is backported? I’m not familiar with C. Nice tool btw.

**Comment by hippie68** [comment]
It searches the filename for "BP" or "Backport", and it also searches the param.sfo file for SDK 5.05 and the changelog file for "Backport". So while being pretty accurate, there's no 100% reliable method being used.

**Comment by pearlxcore** [comment]
Most backport pkg has “Backport” in changelog?

**Comment by hippie68** [comment]
Not sure. It's more of a "nice to have" additional check that I added because I have the changelog loaded anyway. I wouldn't rely on it.
